#
# Copyright (c) 2020 Ubique Innovation AG <https://www.ubique.ch>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
#

spring:
  profiles.active: ${SPRING_PROFILES_ACTIVE:local-sedia,jwt}
  sleuth.log.slf4j.enabled: true

management.endpoints.enabled-by-default: false

server:
  error.whitelabel.enabled: true
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/plain
      - text/xml
  http2:
    enabled: true
  port: ${SERVER_PORT:8080}

logging:
  group:
    cleanup:
      - org.dpppt.backend.sdk.ws.config.WSSediaConfig
      - org.dpppt.backend.sdk.data.gaen.JDBCGAENDataServiceImpl
  level:
    root: info
    cleanup: warn
    org.flywaydb: WARN
    org.dpppt.backend.sdk.gaen.FakeKeyService: INFO
    org.dpppt: debug
  pattern:
    console: '%d %p [%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-B3-ParentSpanId:-},%X{X-Span-Export:-}] [%c] - <%m>%n'
    file: '%d %p [%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-B3-ParentSpanId:-},%X{X-Span-Export:-}] [%c] - %m%n'

#  file:
#    name: dp3t-ws.log
#    max-size: 512KB
#    max-history: 3

#-------------------------------------------------------------------------------
# JDBC Config
#-------------------------------------------------------------------------------
datasource:
  url: jdbc:postgresql://localhost:5432/dpppt
  username: dpppt
  password: dpppt
  driverClassName: org.postgresql.ds.PGSimpleDataSource

ws:
  exposedlist.cachecontrol: 5
  app.source: org.dpppt.demo
  headers:
    protected: X-HELLO,X-BATCH-RELEASE-TIME
    debug: true

springdoc:
  paths-to-match: /v1/gaen/**
  #packagesToScan: org.dpppt.backend.sdk
  api-docs:
    path: /openapi/api-docs
    enabled: ${OPENAPI_ENABLED:true}
  swagger-ui:
    path: /openapi/ui
    enabled: ${OPENAPI_ENABLED:true}

application:
  openapi:
    title: DP3T API
    description: DP3T API
    version: '@project.version@'
    terms-of-service: http://sedia.com/
  endpoint:
    validation:
      url: ${TAN_VALIDATION_URL:https://krthidzr17.execute-api.eu-west-1.amazonaws.com/verification/tan/verify}
      enabled: ${TAN_VALIDATION_ENABLED:true}
