#
# Copyright (c) 2020 Ubique Innovation AG <https://www.ubique.ch>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
#

spring:
  profiles.active: ${SPRING_PROFILES_ACTIVE:radarcovid-local,jwt}
  application:
    name: dpppt
  sleuth:
    log.slf4j:
      enabled: true
      whitelisted-mdc-keys:
        - X-Amz-Cf-Id
    keys.http.headers: X-Amz-Cf-Id
    propagation-keys:
      - X-Amz-Cf-Id
    baggage:
      remote-fields: X-Amz-Cf-Id
      correlation-fields: X-Amz-Cf-Id

cloud:
  aws:
    region:
      auto: ${CLOUD.AWS.REGION.AUTO:false}
      static: ${CLOUD.AWS.REGION.STATIC:eu-west-1}
    stack:
      auto: ${CLOUD.AWS.STACK.AUTO:false}

management.endpoints.enabled-by-default: false

server:
  error.whitelabel.enabled: true
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/plain
      - text/xml
  http2:
    enabled: true
  port: ${SERVER_PORT:8080}

logging:
  group:
    cleanup:
      - org.dpppt.backend.sdk.ws.config.WSSediaConfig
      - org.dpppt.backend.sdk.data.gaen.JDBCGAENDataServiceImpl
      - org.dpppt.backend.sdk.data.JDBCDPPPTDataServiceImpl
      - org.dpppt.backend.sdk.data.JDBCRedeemDataServiceImpl
  level:
    root: info
    cleanup: warn
    org.springframework: warn
    org.flywaydb: warn
    com.amazonaws: error
    org.dpppt.backend.sdk.data.gaen.fakekeyservice: info
    org.dpppt.backend.sdk.ws.radarcovid: debug
    org.dpppt.backend.sdk.ws.security.gaen: debug
    org.dpppt: info
  pattern:
    console: '[%-5level] [%X{X-B3-TraceId:-},%X{X-Amz-Cf-Id:-}] - %c{1} - %msg%n'

#-------------------------------------------------------------------------------
# JDBC Config
#-------------------------------------------------------------------------------
datasource:
  url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/dpppt}
  username: ${DATASOURCE_USER:dpppt}
  password: ${DATASOURCE_PASS:dpppt}
  schema: ${DATASOURCE_SCHEMA:dpppt}
  driverClassName: org.postgresql.ds.PGSimpleDataSource
  failFast: ${DATASOURCE_FAIL_FAST:true}
  maximumPoolSize: ${DATASOURCE_MAX_POOL_SIZE:5}
  maxLifetime: ${DATASOURCE_MAX_LIFE_TIME:1700000}
  idleTimeout: ${DATASOURCE_IDLE_TIMEOUT:600000}
  connectionTimeout: ${DATASOURCE_CONNECTION_TIMEOUT:30000}
  flyway.load: ${DATASOURCE_FLYWAY_LOAD:true}

ws:
  exposedlist:
    cachecontrol: ${WS_EXPOSEDLIST_CACHECONTROL:300000}
    batchlength: ${WS_EXPOSEDLIST_BATCHLENGTH:7200000}
    requestTime: ${WS_EXPOSEDLIST_REQUESTTIME:1500}
  gaen:
    randomkeysenabled: ${WS_GAEN_RANDOMKEYSENABLED:false}
    randomkeyamount: ${WS_GAEN_RANDOMKEYAMOUNT:10}
  retentiondays: ${WS_RETENTIONDAYS:14}
  app:
    source: ${WS_APP_SOURCE:org.dpppt.demo}
    key_size: ${WS_APP_KEY_SIZE:32}
    ios.bundleId: ${WS_APP_IOS_BUNDLEID:org.dpppt.ios.demo}
    android.packageName: ${WS_APP_ANDROID_PACKAGENAME:org.dpppt.android.demo}
    gaen:
      keyVersion: ${WS_APP_GAEN_KEYVERSION:v1}
      keyIdentifier: ${WS_APP_GAEN_KEYIDENTIFIER:214}
      algorithm: ${WS_APP_GAEN_ALGORITHM:1.2.840.10045.4.3.2}
      region: ${WS_APP_GAEN_REGION:es}
      key_size: ${WS_APP_GAEN_KEY_SIZE:16}
    jwt:
      algorithm: ${WS_APP_JWT_ALGORITHM:EC}
      publickey: ${WS_APP_JWT_PUBLICKEY:LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHYk1CQUdCeXFHU000OUFnRUdCU3VCQkFBakE0R0dBQVFCYndNcHNzcFRPRHhJSVYvU3VsbGdTNFRUWTNBVgpmNjYrYUgyVkNXWmFDM2k1b2dmcW8yT1JJQ1FoZkc2MHdWRHp1U2pCQklaaTYxbVZ3QXk1cXJUS0hib0F4QzFpCnJibk1YOG9rUSthamZHRy80UE1yOWpoVHFKamkzY3ZDeU4xQWY2RWY3Z0p6WEtSYVhmdWFyTFRNVWZvV2NXMkkKWXBFOXROSXMzSExmUGczSHJpRT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==}
  headers:
    protected: ${WS_HEADERS_PROTECTED:X-HELLO,X-BATCH-RELEASE-TIME}
    debug: ${WS_HEADERS_DEBUG:true}
  ecdsa.credentials:
    privateKey: ${GAEN_CREDENTIALS_PRIVATE_KEY:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSHVBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFqQklIV01JSFRBZ0VCQkVJQTVvRVgvV0srNG1PZlZFK0gKWXVXN2RCUEsvV1JXYS80dGFBU0YxVkx1UHMyMVltVE9BQzdyamk0WmdZWk9scXNVYTc3VndXYmVJZ1RKR25KeAo5bnZhdDNDaGdZa0RnWVlBQkFBYjExQTl1VHdnamJpSnFNOGdvUEJCTmd1eHNkaHkxMTN4SzlFY2lpMUQybjA4Ck5KazloNDc0bzhhU0tFWUpTSnd6MmphL1gzZ2RMV0tPNmhOWmhxcWdDZ0V1dHEzQWh3WTJOOXRXOXZwVFJTbzAKTklCRW9wTEh2SkdOaVU1NEZ6c3V2dDJ3Z3ZrNFY2N2t4UUtJT2JNRkdnaVVWVERLWTBmQ0V0cWFJcW9RdE5qYgovdz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K}
    publicKey: ${GAEN_CREDENTIALS_PUBLIC_KEY:LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHYk1CQUdCeXFHU000OUFnRUdCU3VCQkFBakE0R0dBQVFBRzlkUVBiazhJSTI0aWFqUElLRHdRVFlMc2JIWQpjdGRkOFN2UkhJb3RROXA5UERTWlBZZU8rS1BHa2loR0NVaWNNOW8ydjE5NEhTMWlqdW9UV1lhcW9Bb0JMcmF0CndJY0dOamZiVnZiNlUwVXFORFNBUktLU3g3eVJqWWxPZUJjN0xyN2RzSUw1T0ZldTVNVUNpRG16QlJvSWxGVXcKeW1OSHdoTGFtaUtxRUxUWTIvOD0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==}

springdoc:
  paths-to-match: /v1/gaen/**
  #packagesToScan: org.dpppt.backend.sdk
  api-docs:
    path: /openapi/api-docs
    enabled: ${OPENAPI_ENABLED:true}
  swagger-ui:
    path: /openapi/ui
    enabled: ${OPENAPI_ENABLED:true}

application:
  openapi:
    title: DP3T API
    description: DP3T API
    version: '@project.version@'
    terms-of-service: http://sedia.com/
  endpoint:
    validation:
      url: ${TAN_VALIDATION_URL:}
      enabled: ${TAN_VALIDATION_ENABLED:false}
  response:
    retention:
      enabled: ${RESPONSE_RETENTION_ENABLED:false}
      time:
        exposed: ${RESPONSE_RETENTION_TIME_EXPOSED:1000} # milliseconds
  log:
    enabled: ${LOGGABLE_ENABLED:false}